---
resource_types:
  - name: irccat-resource
    type: docker-image
    source:
      repository: haiku/irccat-resource
roles:
  - name: owner
    github:
      teams: ["haiku:infrastructure"]
    local:
      users: ["admin"]
resources:
  - name: haiku-git
    type: git
    icon: git
    source:
      uri: https://review.haiku-os.org/haiku.git
      branch: ((branch))
  - name: irc
    type: irccat-resource
    icon: bullhorn
    source:
      uri: https://build.haiku-os.org/irccat/send
      secret: ((irccat-secret))
task-build-image: &task-build-image
  platform: linux
  image_resource:
    type: registry-image
    source: { repository: haiku/toolchain-worker-((branch)) }
  inputs:
    - name: haiku-git
  outputs:
    - name: generated.((arch))
  run:
    path: /bin/bash
    args:
      - -c
      - |
        cd generated.((arch))
        TOOLCHAIN_PRIMARY=""
        TOOLCHAIN_SECONDARY=""
        case "((arch))" in
            "x86_gcc2h")
                PRI_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86_gcc2)
                SEC_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86)
                TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-x86_gcc2/bin/${PRI_TRIPLET}-"
                TOOLCHAIN_SECONDARY="--cross-tools-prefix /toolchains/cross-tools-x86/bin/${SEC_TRIPLET}-"
                ;;
            "x86_64h")
                PRI_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86_64)
                SEC_TRIPLET=$(../haiku-git/build/scripts/find_triplet x86)
                TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-x86_64/bin/${PRI_TRIPLET}-"
                TOOLCHAIN_SECONDARY="--cross-tools-prefix /toolchains/cross-tools-x86/bin/${SEC_TRIPLET}-"
                ;;
            *)
                PRI_TRIPLET=$(../haiku-git/build/scripts/find_triplet ((arch)))
                TOOLCHAIN_PRIMARY="--cross-tools-prefix /toolchains/cross-tools-((arch))/bin/${PRI_TRIPLET}-"
                TOOLCHAIN_SECONDARY=""
                ;;
        esac
        ../haiku-git/configure $TOOLCHAIN_PRIMARY $TOOLCHAIN_SECONDARY
        jam -j4 -q @((profile))-((media))
# Jobs
jobs:
  - name: haiku-((branch))-((arch))
    public: true
    on_success:
      try:
        put: irc
        params:
          message: "haiku.%PURPLE((branch))%NORMAL: build of %BLUE((arch))%NORMAL was %GREENsuccessful%NORMAL ${BUILD_URL}"
    on_failure:
      try:
        put: irc
        params:
          message: "haiku.%PURPLE((branch))%NORMAL: build of %BLUE((arch))%NORMAL %REDfailed%NORMAL ${BUILD_URL}"
    plan:
      - get: haiku-git
        trigger: true
      - task: build-((branch))-((profile))-((media))
        config:
          << : *task-build-image
