#
# Haiku's continious integration
#
# Description:
#   These containers manage builds of various components of Haiku such as package
#   repositories, nightly os images, release os images, and haikuports builds.
#
version: "3.2"
services:
  www:
    image: dragas/thttpd
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
    networks:
      - ingress_ci
    volumes:
      - ./data/static-html/build:/var/www/http:z
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ingress_ci"
      - "traefik.basic.frontend.rule=Host:build.${DOMAIN}"
      - "traefik.basic.port=80"
  buildmaster_master_x86_64:
    image: haikuports/buildmaster
    deploy:
      placement:
        constraints: [node.labels.build == true ]
    command: loop
    networks:
      - private
    volumes:
      - sources:/var/sources:z
      - data_master_x86_64:/var/buildmaster:z
      - packages:/var/packages:z
    environment:
      REPOSITORY_TRIGGER_URL: "https://depot.haiku-os.org/__repository/haikuports/source/haikuports_x86_64/import"
  buildmaster_master_x86_gcc2:
    image: haikuports/buildmaster
    deploy:
      placement:
        constraints: [node.labels.build == true ]
    command: loop
    networks:
      - private
    volumes:
      - sources:/var/sources:z
      - data_master_x86_gcc2:/var/buildmaster:z
      - packages:/var/packages:z
    environment:
      REPOSITORY_TRIGGER_URL: "https://depot.haiku-os.org/__repository/haikuports/source/haikuports_x86_gcc2/import"
  buildmaster_teleport:
    image: mmlr/teleport
    command: server 5825 auth.db
    networks:
      - private
    ports:
      - "0.0.0.0:5825:5825"
    volumes:
      - teleport:/var/teleport
  buildmaster_frontend:
    image: haikuports/buildmaster-frontend
    deploy:
      placement:
        constraints: [node.labels.build == true ]
    networks:
      - ingress_ci
      - private
    volumes:
      - sources:/var/sources:ro
      - data_master_x86_gcc2:/var/instances/master/x86_gcc2:ro
      - data_master_x86_64:/var/instances/master/x86_64:ro
      - packages:/var/instances/haikuports:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ingress_ci"
      - "traefik.basic.frontend.rule=Host:build.${DOMAIN};PathPrefixStrip:/buildmaster/"
      - "traefik.basic.port=80"
  concourse:
    image: haiku/concourse-web:6.7
    command: web
    environment:
      CONCOURSE_EXTERNAL_URL: https://ci.haiku-os.org
      #CONCOURSE_EXTERNAL_URL: https://build.haiku-os.org/concourse/
      CONCOURSE_TSA_BIND_PORT: 8022
      CONCOURSE_CONTAINER_PLACEMENT_STRATEGY: limit-active-tasks
      CONCOURSE_MAX_ACTIVE_TASKS_PER_WORKER: 2
      CONCOURSE_SESSION_SIGNING_KEY: /keys/session_signing_key
      CONCOURSE_TSA_HOST_KEY: /keys/tsa_host_key
      CONCOURSE_TSA_AUTHORIZED_KEYS: /keys/authorized_worker_keys
    networks:
      - ingress_ci
      - support_default
    ports:
      - target: 8022
        published: 8022
    volumes:
      - concourse_keys:/keys
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ingress_ci"
      # Ideally this should be at build.haiku-os.org/concourse, but the app
      # doesn't like prefix paths.
      - "traefik.basic.frontend.rule=Host:ci.${DOMAIN}"
      - "traefik.basic.port=8080"
  irccat:
    image: irccloud/irccat:latest
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - ingress_ci
    volumes:
      - ./data/irccat/irccat.json:/etc/irccat.json:z
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ingress_ci"
      - "traefik.basic.frontend.rule=Host:build.${DOMAIN};PathPrefixStrip:/irccat"
      - "traefik.basic.port=8045"
volumes:
  concourse_keys:
  teleport:
  sources:
  packages:
    driver: rexray/dobs
    driver_opts:
      size: 200
  data_master_x86_gcc2:
  data_master_x86_64:
networks:
  private:
    driver: overlay
  support_default:
    external: true
  ingress_ci:
    external: true
