#
# Haiku's ingress
#
# Description:
#   All inbound http/https traffic flows through here into the destination containers.
#   Traefik routes data to destination containers by polling docker for labels on each
#   container about what should be exposed where.
#   All http/https traffic should flow through here!
#
#   Since the ingress is critical to service "all requests", we run 2 of them and roll
#   updates across one replica at a time.
#
version: "3.2"
services:
  admin:
    image: alpine:latest
    command: "sleep 86400"
    networks:
      - ci
      - community
      - cdn
      - dev
      - support_default
      - sysadmin
  traefik:
    # Traefik connects to docker and reads labels to form routes
    # Traefik also handles letsencrypt renewals
    #
    # EDIT: DO NOT UPGRADE TO 2.x! It requires a bunch of updates to *ALL* yaml!
    image: traefik:v1.7.26
    deploy:
      replicas: 1
      placement:
        constraints: [node.role==manager]
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
    networks:
      default:
      support_default:
      ci:
      community:
      cdn:
      dev:
        aliases:
          - eu.hpkg.haiku-os.org
      sysadmin:
    ports:
      # workaround for https://github.com/moby/moby/issues/25526
      # Warning: host prevents multiple traefik instances on same node!
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - /var/log/traefik:/logs:z
      - ./data/traefik/traefik.toml:/traefik.toml:z
      - traefik_acme:/acme:z
volumes:
  traefik_acme:
networks:
  support_default:
    external: true
  dev:
    driver: overlay
  cdn:
    driver: overlay
  ci:
    driver: overlay
  community:
    driver: overlay
  sysadmin:
    driver: overlay
    attachable: true
