#
# Haiku sysadmin services
#
# Description:
#   Various tools to monitor our containers and alert us about potential issues.
#
version: "3.2"
services:
  auth:
    image: quay.io/keycloak/keycloak:11.0.2
    networks:
      - ingress_sysadmin
      - support_default
    volumes:
      - ./data/keycloak/theme:/opt/jboss/keycloak/themes/haiku:z
    environment:
      KEYCLOAK_FRONTEND_URL: https://auth.haiku-os.org/auth
      KEYCLOAK_DEFAULT_THEME: haiku
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: coolpass
      DB_VENDOR: h2
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ingress_sysadmin"
      - "traefik.basic.frontend.rule=Host:auth.${DOMAIN}"
      - "traefik.basic.port=8080"
  #node_exporter:
  #  image: haiku/node_exporter
  #  networks:
  #    - ingress_sysadmin
  #  volumes:
  #    - /sys:/host/sys:ro,rslave
  #    - /proc:/host/proc:ro,rslave
  #  command: --path.procfs /host/proc --path.sysfs /host/sys
  prometheus:
    image: prom/prometheus
    networks:
      - ingress_sysadmin
    volumes:
      - ./data/metrics/prometheus.yml:/etc/prometheus/prometheus.yml:z
      - prometheus_data:/prometheus:z
  grafana:
    image: grafana/grafana
    networks:
      - ingress_sysadmin
    environment:
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "smtp:25"
      GF_SMTP_FROM_ADDRESS: "admin@metrics.${DOMAIN}"
      GF_SERVER_ROOT_URL: "https://metrics.${DOMAIN}/grafana/"
    volumes:
      - grafana_data:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ingress_sysadmin"
      - "traefik.basic.frontend.rule=Host:metrics.${DOMAIN};PathPrefixStrip:/grafana/"
      - "traefik.basic.port=3000"
  fathom:
    image: usefathom/fathom:latest
    depends_on:
      - postgres
    networks:
      - ingress_sysadmin
      - support_default
    volumes:
      - fathom_secrets:/var/lib/fathom
    command: /app/fathom --config=/var/lib/fathom/config.env server
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ingress_sysadmin"
      - "traefik.basic.frontend.rule=Host:metrics.${DOMAIN}"
      - "traefik.basic.port=8080"
volumes:
  fathom_secrets:
  prometheus_data:
  grafana_data:
networks:
  private:
    driver: overlay
  support_default:
    external: true
  ingress_sysadmin:
    external: true
